
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcveqospcsndyhetxzdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdmVxb3NwY3NuZHloZXR4emRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjY2MzMsImV4cCI6MjA2MzUwMjYzM30.9eJ4T7ckC1QUd3LMsGuyXuTAlyZCuMO0d0rA9sC5eJ0";

// Configure Supabase client with explicit settings
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web'
    }
  }
});
